// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzvrjSxK1tpWU7xuUNSVaoPmDFul2_AUk',
    appId: '1:1042079948986:web:66cccc6fabcef2b5122283',
    messagingSenderId: '1042079948986',
    projectId: 'decider-81156',
    authDomain: 'decider-81156.firebaseapp.com',
    storageBucket: 'decider-81156.appspot.com',
    measurementId: 'G-E4XJNF89W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxWt4wmQnFWJzdTqywdYoVAxNT4silYok',
    appId: '1:1042079948986:android:6060bc8c8c48b643122283',
    messagingSenderId: '1042079948986',
    projectId: 'decider-81156',
    storageBucket: 'decider-81156.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUX5qq5EldLCWzdNUdEfZU18OnooZNoQs',
    appId: '1:1042079948986:ios:f7d00600828cbfd1122283',
    messagingSenderId: '1042079948986',
    projectId: 'decider-81156',
    storageBucket: 'decider-81156.appspot.com',
    iosBundleId: 'com.gustavodscruz.decider',
  );
}
